import test from 'node:test';import assert from 'node:assert/strict';
import {analyze,analyzeGroup,parseChat,level} from '../src/engine.js';
import {RULES} from '../src/rules.js';
import en from '../src/locales/en.js';import hi from '../src/locales/hi.js';
const ids=t=>analyze(t).flags.map(f=>f.id);
test('guaranteed and unrealistic returns',()=>{const i=ids('Guaranteed 40% returns every month');assert.ok(i.includes('guarantee')&&i.includes('unreal'))});
test('negation guard: "no scheme can guarantee" is not flagged',()=>assert.ok(!ids('No scheme can guarantee returns.').includes('guarantee')));
test('negation guard does not hide a real claim',()=>assert.ok(ids('Do not miss! Guaranteed profit.').includes('guarantee')));
test('OTP request flagged, OTP warning not',()=>{assert.ok(ids('Please share your OTP now').includes('otp'));assert.ok(!ids('Never share OTP with anyone').includes('otp'))});
test('invalid SEBI number (8 digits) flagged',()=>assert.ok(ids('Reg No INH00012345').includes('regbad')));
test('valid-format SEBI number is a note, not a flag',()=>{const r=analyze('Reg No INH000012345');assert.ok(!r.flags.some(f=>f.id==='regbad'));assert.equal(r.notes[0].id,'regok')});
test('look-alike domain flagged, official domain noted',()=>{assert.ok(ids('visit https://zerodha-pro.xyz').includes('lookalike'));const r=analyze('log in at https://groww.in');assert.equal(r.flags.length,0);assert.equal(r.notes[0].id,'siteok')});
test('homoglyph domain (grovvv/0 for o) caught',()=>assert.ok(ids('open upst0x.com now').includes('lookalike')));
test('personal UPI flagged, SEBI @valid handle noted',()=>{assert.ok(ids('pay to abc@ybl').includes('upi'));const r=analyze('pay to abc.brk@validhdfc');assert.ok(!r.flags.some(f=>f.id==='upi'));assert.equal(r.notes[0].id,'validok')});
test('Hindi and Hinglish scams detected',()=>{assert.ok(ids('पक्का मुनाफा, 40% हर महीने गारंटी').includes('guarantee'));assert.ok(ids('kisi ko mat batana').includes('secret'))});
test('score is bounded and levels map correctly',()=>{const s=analyze('x'.repeat(30)).score;assert.equal(s,0);assert.equal(level(0),'lo');assert.equal(level(30),'mid');assert.equal(level(80),'hi')});
test('chat parsing splits WhatsApp export lines',()=>assert.equal(parseChat('12/09/2026, 10:02 - A: hi\n12/09/2026, 10:03 - B: yo\nmore').length,2));
test('group profiler raises group-level signals',()=>{const g=analyzeGroup(`12/09/2026, 10:02 - Admin: Guaranteed 30% monthly returns.\n12/09/2026, 10:05 - Admin: Buy above 245 target 260 stop loss 238.\n12/09/2026, 10:06 - Admin: Sure shot call, upper circuit.\n12/09/2026, 10:30 - Neha: I made 18000 today!`);assert.ok(g.flags.some(f=>f.id==='tipheavy'));assert.ok(g.flags.some(f=>f.id==='onevoice'));assert.equal(level(g.score),'hi')});
test('every rule and flag id has text in both languages',()=>{const all=[...RULES.map(r=>r.id),'lookalike','tld','short','regbad','regnone','tipheavy','onevoice'];for(const L of [en,hi])for(const id of all)assert.ok(L.rules[id]?.length===2,id);for(const L of [en,hi])for(const id of ['regok','siteok','validok'])assert.ok(L.notes[id],id)});
test('registration claim without a number is flagged; advice to check registration is not',()=>{assert.ok(ids('Our SEBI registered adviser will call you').includes('regnone'));assert.ok(!ids('Always check SEBI registration at sebi.gov.in').includes('regnone'))});
